//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.24 at 07:49:36 PM GMT+07:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nlatysh.ru/common/models")
package ru.nlatysh.common.models;
